f = open('C:/Users/cools/Documents/ARNOV1.txt','r+')
f.write('hello world . how are you all!')
num = f.__sizeof__()
str1 = f.read(num)
print('read the file : ',str1)
print ("Name of the file: ", f.name)
print ("Closed or not : ", f.closed)
print ("Opening mode : ", f.mode)
print ("Softspace flag : ", f.__sizeof__())
